name: Flowly Player CI/CD

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  version:
    runs-on: ubuntu-latest

    outputs:
      version: ${{ steps.get_version.outputs.version }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Get version from package.json
        id: get_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=v$VERSION" >> $GITHUB_OUTPUT

  tag:
    needs: version
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create tag if not exists
        shell: bash
        run: |
          git fetch --tags

          TAG=${{ needs.version.outputs.version }}

          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag already exists"
          else
            git config user.name "github-actions"
            git config user.email "actions@github.com"
            git tag $TAG
            git push origin $TAG
          fi

  build:
    needs: [version, tag]
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Create .env
        shell: bash
        run: |
          echo "YOUTUBE_CLIENT_ID=${{ secrets.YOUTUBE_CLIENT_ID }}" >> .env
          echo "YOUTUBE_CLIENT_SECRET=${{ secrets.YOUTUBE_CLIENT_SECRET }}" >> .env

      - name: Build Windows EXE
        run: npm run build:win

      - name: Setup SSH
        shell: bash
        run: |
          mkdir -p $HOME/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > $HOME/.ssh/github-actions
          chmod 600 $HOME/.ssh/github-actions
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> $HOME/.ssh/known_hosts

      - name: Test SSH Connection
        shell: bash
        run: |
          ssh -i $HOME/.ssh/github-actions -o StrictHostKeyChecking=no \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "echo SSH CONNECTED"

      - name: Upload EXE ke server
        shell: bash
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
        run: |

          echo "Searching EXE files..."

          find dist -type f -name "*.exe" -print0 | while IFS= read -r -d '' file
          do

            filename=$(basename "$file")

            echo "Checking $filename on server..."

            if ssh -i $HOME/.ssh/github-actions -o StrictHostKeyChecking=no $USER@$HOST \
              "test -f /home/jtech/clusters/jauhar/flowlyplayer/public_html/files/$filename"
            then
              echo "$filename already exists. Skipping upload."
            else
              echo "Uploading $filename..."
              scp -i $HOME/.ssh/github-actions -o StrictHostKeyChecking=no "$file" \
              $USER@$HOST:/home/jtech/clusters/jauhar/flowlyplayer/public_html/files/
            fi

          done

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.version.outputs.version }}
          files: dist/*.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
